### ISSUE TITLE
ssl error when datasift-writer tries to connect to https://in.datasift.com

### ISSUE THREAD

**Issue by nwolff** [datasift/datasift-connector#45]
Using the packer distribution from the latest release: https://github.com/datasift/datasift-connector/releases/tag/1.0.15-1

`/var/log/datasift/writer.log` shows:

``` (2015,08,11,15,20,54,(996)) ERROR com.dat.con.wri.BulkManager:282 - Could not connect to ingestion endpoint
 javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
    at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
```

I was able to fix by udgrading the jre to version 8 update 45

**Comment by dugjason** [comment]
Speaking to another customer, I can confirm that this resolved their issues. @AndyJS can we look at upgrading the default version of Java we use please?

**Comment by nwolff** [comment]
Problem is still there in 1.0.19-1  (and upgrading the jdk still fixes the problem)
